pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                bat 'javac Server/Server.java'
            }
        }
        stage('Run') {
            steps {
               bat 'java Server/Server'
        }
    }
  } 
}
